ALTER TABLE course
ADD COLUMN IF NOT EXISTS editor_state JSONB;

ALTER TABLE course
ADD COLUMN IF NOT EXISTS editor_version VARCHAR(50);

ALTER TABLE course
ADD COLUMN IF NOT EXISTS editor_status VARCHAR(50);
