-- Core schema sync for environments that were baselined with partial history.
-- Safe to re-run thanks to IF NOT EXISTS.

-- users
ALTER TABLE users ADD COLUMN IF NOT EXISTS fname VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS lname VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- course
ALTER TABLE course ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS cover_image_url TEXT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS passing_score NUMERIC(5,2);
ALTER TABLE course ADD COLUMN IF NOT EXISTS attempt_limit INTEGER;
ALTER TABLE course ADD COLUMN IF NOT EXISTS duration_min INTEGER;
ALTER TABLE course ADD COLUMN IF NOT EXISTS status VARCHAR(255);
ALTER TABLE course ADD COLUMN IF NOT EXISTS tags VARCHAR(50)[];
ALTER TABLE course ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN;
ALTER TABLE course ADD COLUMN IF NOT EXISTS text_html TEXT;
ALTER TABLE course ADD COLUMN IF NOT EXISTS theme_override JSONB;
ALTER TABLE course ADD COLUMN IF NOT EXISTS layout_mode VARCHAR(255);
ALTER TABLE course ADD COLUMN IF NOT EXISTS layout_meta JSONB;
ALTER TABLE course ADD COLUMN IF NOT EXISTS last_published_at TIMESTAMPTZ;
ALTER TABLE course ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE course ADD COLUMN IF NOT EXISTS extra_infor JSONB;
ALTER TABLE course ADD COLUMN IF NOT EXISTS editor_state JSONB;
ALTER TABLE course ADD COLUMN IF NOT EXISTS editor_version VARCHAR(50);
ALTER TABLE course ADD COLUMN IF NOT EXISTS editor_status VARCHAR(50);
ALTER TABLE course ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- section
ALTER TABLE section ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE section ADD COLUMN IF NOT EXISTS order_index INTEGER;
ALTER TABLE section ADD COLUMN IF NOT EXISTS learning_objective TEXT;
ALTER TABLE section ADD COLUMN IF NOT EXISTS text_html TEXT;
ALTER TABLE section ADD COLUMN IF NOT EXISTS theme_override JSONB;
ALTER TABLE section ADD COLUMN IF NOT EXISTS layout_mode VARCHAR(255);
ALTER TABLE section ADD COLUMN IF NOT EXISTS layout_meta JSONB;

-- page
ALTER TABLE page ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE page ADD COLUMN IF NOT EXISTS order_index INTEGER;
ALTER TABLE page ADD COLUMN IF NOT EXISTS page_type VARCHAR(255);
ALTER TABLE page ADD COLUMN IF NOT EXISTS text_html TEXT;
ALTER TABLE page ADD COLUMN IF NOT EXISTS theme_override JSONB;
ALTER TABLE page ADD COLUMN IF NOT EXISTS layout_mode VARCHAR(255);
ALTER TABLE page ADD COLUMN IF NOT EXISTS layout_type VARCHAR(255);
ALTER TABLE page ADD COLUMN IF NOT EXISTS layout_meta JSONB;

-- content_page
ALTER TABLE content_page ADD COLUMN IF NOT EXISTS layout_mode VARCHAR(100);
ALTER TABLE content_page ADD COLUMN IF NOT EXISTS layout_type VARCHAR(100);
ALTER TABLE content_page ADD COLUMN IF NOT EXISTS layout_meta JSONB;

-- content_block
ALTER TABLE content_block ADD COLUMN IF NOT EXISTS order_index INTEGER;
ALTER TABLE content_block ADD COLUMN IF NOT EXISTS block_type VARCHAR(50);
ALTER TABLE content_block ADD COLUMN IF NOT EXISTS text_html TEXT;
ALTER TABLE content_block ADD COLUMN IF NOT EXISTS theme_override JSONB;
ALTER TABLE content_block ADD COLUMN IF NOT EXISTS layout_meta JSONB;

-- quiz_page
ALTER TABLE quiz_page ADD COLUMN IF NOT EXISTS passing_score NUMERIC(5,2);
ALTER TABLE quiz_page ADD COLUMN IF NOT EXISTS attempt_allowed INTEGER;
ALTER TABLE quiz_page ADD COLUMN IF NOT EXISTS theme_override JSONB;
ALTER TABLE quiz_page ADD COLUMN IF NOT EXISTS layout_mode VARCHAR(255);
ALTER TABLE quiz_page ADD COLUMN IF NOT EXISTS layout_meta JSONB;
ALTER TABLE quiz_page ADD COLUMN IF NOT EXISTS template_data JSONB;

-- scorm_export_config
ALTER TABLE scorm_export_config ADD COLUMN IF NOT EXISTS extra_config JSONB;
ALTER TABLE scorm_export_config ADD COLUMN IF NOT EXISTS theme_config JSONB;
